name: Deploy CAGED Query Lambda

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-dev:
    uses: Stentzler/caged-lambda-cicd/.github/workflows/lambda-python-zip.yml@main
    with:
      environment_name: dev
      function_name: caged-dev-query
      alias_name: dev
      zip_path: dist/caged-query-lambda.zip
    secrets: inherit
